name: combined_barcode_scanner_blue_bird
description: Combined Barcode scanner package that interfaces with blue bird scanners
version: 1.1.0
homepage: https://github.com/icapps/combined_barcode_scanner
repository: https://github.com/icapps/combined_barcode_scanner

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  combined_barcode_scanner: ^1.1.0
  flutter:
    sdk: flutter
  blue_bird_scanner: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

#dependency_overrides:
# combined_barcode_scanner:
#   path: ../..

flutter:
